name: "build-and-tests"
on:
  pull_request:
  push:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  build:
    name: Check build & tests
    runs-on: apps-ci
    timeout-minutes: 120
    steps:
      
    - name: Remove any previous hook 🥸
      run: rm -rf .git/hooks

    - name: Checkout 🔎
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Cache for Gems 💎
      uses: actions/cache@v3
      with:
        path: |
          .gems
          ~/.bundle
        key: ${{ runner.os }}-cache-gems-${{ hashFiles('**/Gemfile.lock') }}

    - name: Rake ⚙️
      run: rake

    - name: Run tests ⚙️
      run: rake test

    - name: Generate lcov file 📈
      run: |
        xcrun llvm-cov export \
          -format="lcov" \
          --ignore-filename-regex=".build|.test-bundle|Tests/" \
          .build/debug/MiniPackageTests.xctest/Contents/MacOS/MiniPackageTests \
          -instr-profile .build/debug/codecov/default.profdata \
          > report.lcov

    - name: Upload package tests coverage to Codecov 📋
      uses: codecov/codecov-action@v3.1.1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: report.lcov
        flags: package
        fail_ci_if_error: true
        name: codecov-package
        gcov_ignore: Tests/*

    - name: Save Output 📦
      uses: actions/upload-artifact@v3
      with:
        name: output
        path: ${{ github.workspace }}/report.lcov
